### ISSUE TITLE
Good idea but Windows 10 can do better

### ISSUE THREAD

**Issue by SebastianSchuetze** [swharden/Tmoji#2]
Check this out and press "Windows Key + ;" or "Windows Key + ." ;-)

![image](https://user-images.githubusercontent.com/7256168/145068061-deb2301b-d6e1-4c4f-9d7d-6a7ecda9d0e8.png)

**Comment by swharden** [comment]
Thanks for the tip @SebastianSchuetze! See this discussion in https://github.com/swharden/Tmoji/issues/1#issuecomment-747797077 and https://github.com/swharden/Tmoji/issues/1#issuecomment-778640919

TLDR: Tmoji is faster than a multi-page pop-up app that requires scrolling and searching
